humanml3d:
    NAME: humanml3d
    DATA_ROOT: /data/anders/data/humanml3d
    MOTION_FILENAME: motion.pt
    CACHE: False

interhuman:
    NAME: interhuman
    DATA_ROOT: /data/anders/data/interhuman/subset/
    MOTION_FILENAME: motion.pt
    CACHE: False

# teton:
#     NAME: teton
#     DATA_ROOT: /data/anders/data/teton_data/train
#     MOTION_FILENAME: optimized_motion_transformed.pt
#     CACHE: True
