humanml3d:
    NAME: humanml3d
    DATA_ROOT: /work3/s183926/data/humanml3d
    MOTION_FILENAME: motion.pt
    CACHE: True

interhuman:
    NAME: interhuman
    DATA_ROOT: /work3/s183926/data/interhuman
    MOTION_FILENAME: motion.pt
    CACHE: True

# teton:
#     NAME: teton
#     DATA_ROOT: /data/anders/data/teton_data/train
#     MOTION_FILENAME: optimized_motion_transformed.pt
#     CACHE: True
