NAME: InterGen
NUM_LAYERS: 8
NUM_HEADS: 8
DROPOUT: 0.1
INPUT_DIM: 291 # 3 translation + 24 * 3*2 rotations + 24*3 joints + 24x3 vels
LATENT_DIM: 1024
FF_SIZE: 2048
ACTIVATION: gelu
CHECKPOINT: checkpoints/IG-S-8/model/epoch=399-step=124000.ckpt
SMPL_MODEL_PATH: weights/smpl/basicmodel_neutral_lbs_10_207_0_v1.1.0.pkl

DIFFUSION_STEPS: 1000
BETA_SCHEDULER: cosine
SAMPLER: uniform

MOTION_REP: global
FINETUNE: False

T_BAR: 700

CONTROL: text
STRATEGY: ddim100
CFG_WEIGHT: 3

NUM_ACTIONS: 12
NUM_CLASSES: 3
