GENERAL:
  EXP_NAME: IG-S-8
  CHECKPOINT: ./checkpoints
  LOG_DIR: ./log

TRAIN:
  LR: 1e-4
  WEIGHT_DECAY: 0.00002
  BATCH_SIZE: 64 # 128
  EPOCH: 500
  STEP: 1_000_000
  LOG_STEPS: 10
  SAVE_STEPS: 20000
  SAVE_EPOCH: 10
  RESUME: checkpoints/IG-S-8/model/epoch=159-step=12800-v1.ckpt
  NUM_WORKERS: 32
  MODE: finetune
  LAST_EPOCH: 0
  LAST_ITER: 0
