GENERAL:
  EXP_NAME: CONDITIONAL
  CHECKPOINT: /work3/s183926/checkpoints
  LOG_DIR: ./log

TRAIN:
  LR: 1e-4
  WEIGHT_DECAY: 0.00002
  BATCH_SIZE: 128
  EPOCH: 500
  LOG_STEPS: 10
  SAVE_EPOCH: 10
  RESUME: /work3/s183926/checkpoints/CONDITIONAL/model/epoch=299-step=40960.ckpt
  NUM_WORKERS: 16
